CREATE TABLE IF NOT EXISTS public.sensors
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255),
    location character varying(255),
    model character varying(255),
    name character varying(255),
    range_from smallint NOT NULL,
    range_to smallint NOT NULL,
    type character varying(255),
    unit character varying(255),
    CONSTRAINT sensors_pk PRIMARY KEY (id)
);

--rollback DROP TABLE sensors;
